### ISSUE TITLE
The solid primary color button has poor contrast

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-boolean-models-website#5]
The blue/red primary buttons are nice, but the black-on-blue is not a super easy to read combination. I propose we either:
 1. Change to stroked buttons instead of solid buttons (i.e. just the border has color, the background is white/transparent).
 2. Change the text color to white. It looks worse on red, but better on blue, which is the state where most people will read it.

**Comment by StarLord1337** [comment]
I cant replicate the same issue. When I run the project, all buttons are white text color.
